# This source file is part of the Swift.org open source project
#
# Copyright (c) 2022 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See http://swift.org/LICENSE.txt for license information
# See http://swift.org/CONTRIBUTORS.txt for Swift project authors

version: "3"

services:

  docker-setup:
    image: fedora:34
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: fedora:34
    depends_on:
      - docker-setup
    volumes:
      - ../../Fedora/34:/code/Fedora/34:z
      - ../../Shared:/code/Shared:z
      - ./.output:/output:z
    working_dir: /code/Fedora/34
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  build:
    <<: *common
    command: /bin/bash -cl "./build_rpm.sh"

  createrepo:
    <<: *common
    command: /bin/bash -cl "./createrepo_rpm.sh"

  shell:
    <<: *common
    entrypoint: /bin/bash -l
